---
abstract: 'objects to convert alphabets'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Convert-Moji
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/benkasminbullock/Convert-Moji/issues
  repository: https://github.com/benkasminbullock/Convert-Moji
version: 0.07
